import { ExtendedProductDetails, Product } from '@/types'

export function getExtendedProductData(product: Product): ExtendedProductDetails {
  const isNew = product.condition === 'New'

  // Custom narrative generated by category types
  let description = `This ${product.year} ${product.brand} ${product.title} has been rigorously inspected to meet strict trail-ready standards. Engineered with a powerful ${product.engineSize} power plant, it is designed to deliver consistent performance across demanding environments.`

  let features = [
    'Heavy-duty responsive suspension architecture',
    'Reinforced off-road chassis configuration',
    'Electronic fuel injection (EFI) optimization',
    'All-terrain high-traction tread package',
  ]

  if (product.category === 'ATV' || product.category === 'UTV') {
    description = `Dominate the dirt with this ${product.year} ${product.brand} ${product.title}. Featuring a high-output ${product.engineSize} engine system, automatic high-low variable transmission, and robust selectable 4WD capabilities. ${isNew ? 'Fresh from the factory floor and completely unridden.' : 'Lightly weathered, perfectly tuned, and field-tested by certified technicians.'} Complete your down payment online and claim ownership instantly.`
    features = [
      'Selectable 4WD / 2WD with locking front differential',
      'Heavy-duty front cargo rack and integrated hitch receiver',
      'Electronic Power Steering (EPS) system configuration',
      'Pre-wired winch mounting plate housing matrix',
    ]
  } else if (product.category === 'Dirt Bike') {
    description = `Carve tight tracks with agility. This ${product.year} ${product.brand} ${product.title} pairs a lightweight chassis frame with a high-revving ${product.engineSize} power core. Tuned for swift cornering, aggressive low-end torque profiles, and reliable landing impact absorption.`
    features = [
      'Competition-tuned inverted front forks with adjustable rebound',
      'Lightweight aluminum perimeter frame layout',
      'Race-spec hydraulic disc brake systems front & rear',
      'Launch control engine mapping management modules',
    ]
  } else if (product.category === 'Jet Ski') {
    description = `Slice through wakes and open water. The ${product.year} ${product.brand} ${product.title} provides immense power through an optimized ${product.engineSize} marine propulsion system, complete with high-flow jet pumps and quick-response trim controls.`
    features = [
      'High-displacement marine engine with closed-loop cooling',
      'Ergonomic bolster seating built for high-speed balance',
      'Axial-flow single-stage jet pump propulsion system',
      'Intuitive electronic reverse and deceleration system',
    ]
  }

  const specs = [
    { label: 'Stock Number', value: product.stockNumber },
    { label: 'Condition Status', value: product.condition },
    { label: 'Model Year', value: String(product.year) },
    { label: 'Engine Size', value: product.engineSize },
    { label: 'Vehicle Class', value: product.category || 'Powersports' },
    { label: 'Manufacturer', value: product.brand },
  ]

  return { description, features, specs }
}
