import { ReviewItem } from '@/types'

export const EXTENDED_REVIEWS: ReviewItem[] = [
  {
    name: 'Marcus T.',
    location: 'Dallas, TX',
    machine: '2026 Polaris Sportsman 850',
    rating: 5,
    text: 'Honestly, I was skeptical about the no-credit-check financing claim because my score is rough after a messy divorce. Walked through the options over the phone with an agent, locked the pricing, and the Sportsman was dropped right at my ranch exactly 5 days later. Flawless process.',
    tags: ['Financing', 'Delivery', 'Polaris'],
    date: 'May 18, 2026',
  },
  {
    name: 'Sarah K.',
    location: 'Denver, CO',
    machine: '2025 Can-Am Outlander 1000R',
    rating: 5,
    text: 'The pre-shipment detailing on my Outlander was immaculate—not a single smudge on the plastics. They handled all the cross-state paperwork digitally. This team completely sets the standard for buying utility machines online.',
    tags: ['Delivery', 'Can-Am'],
    date: 'May 10, 2026',
  },
  {
    name: 'David L.',
    location: 'Atlanta, GA',
    machine: '2023 Honda Foreman 4x4',
    rating: 4,
    text: 'Excellent customer service from start to finish. Sifting through inventory choices took me a second, but once I locked the unit, the financing terms were completely straightforward and fair. Delivered safely right to my driveway.',
    tags: ['Financing', 'Honda'],
    date: 'Apr 29, 2026',
  },
  {
    name: 'Robert H.',
    location: 'Phoenix, AZ',
    machine: '2026 Can-Am Outlander MAX',
    rating: 5,
    text: 'First time buying a powersports vehicle online without touching it first. The agents communicated clearly at every stage. Delivery driver was professional and did a thorough walkthrough with me in the driveway.',
    tags: ['Delivery', 'Can-Am'],
    date: 'Apr 15, 2026',
  },
  {
    name: 'Brandon M.',
    location: 'Nashville, TN',
    machine: '2025 Polaris Scrambler 850',
    rating: 5,
    text: 'Zero credit hurdles. I filed the application online, got a call back within two hours with clear terms, confirmed my options, and had the unit delivered that weekend. Absolute game-changer.',
    tags: ['Financing', 'Polaris'],
    date: 'Mar 28, 2026',
  },
  {
    name: 'Garrett W.',
    location: 'Salt Lake City, UT',
    machine: '2026 Polaris RZR XP 1000',
    rating: 5,
    text: 'Financing process was smooth as silk. Got my approval terms within an hour and finalized shipment schedules. The unit arrived enclosed and spotless. Ready for the dunes.',
    tags: ['Financing', 'Delivery', 'Polaris'],
    date: 'Mar 14, 2026',
  },
  {
    name: 'Elena R.',
    location: 'Missoula, MT',
    machine: '2024 Honda Rancher 4x4',
    rating: 5,
    text: 'Needed a workhorse for our property. You cannot beat a Honda for reliability. The transaction was handled perfectly online and transport setup showed up right on schedule.',
    tags: ['Delivery', 'Honda'],
    date: 'Feb 20, 2026',
  },
  {
    name: 'Jackson P.',
    location: 'Orlando, FL',
    machine: '2025 Can-Am Renegade 1000R',
    rating: 5,
    text: 'This machine is an absolute beast. Raw power. The application and delivery matrix felt much smoother than wasting an entire Saturday playing typical dealership finance manager games.',
    tags: ['Financing', 'Can-Am'],
    date: 'Jan 30, 2026',
  },
]
